os: linux
addons:
  apt:
    packages:
      - build-essential
      - doxygen
      - graphviz
      - help2man
      - python-docutils
      - python-pygments
      - pngcrush
language: node_js
node_js:
  - node
services:
  - docker
before_script:
  # Bootstrap only xapian-core for emscripten build.
  - ./setup-emsdk.sh
  - source ./emsdk/emsdk_env.sh
  - ./build-xapian.sh
script:
  - source ./emsdk/emsdk_env.sh
  - node compilermmxapianapi.js --xapiandir=xapian/xapian-core
  - npm run test-no-watch
